version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: gitnest-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    container_name: gitnest-redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    container_name: gitnest-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/gitnest
      - NODE_ENV=development
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
    container_name: gitnest-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000/api/v1
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules 

volumes:
  mongo-data:
