const ACTIVITY_TYPES = Object.freeze({
  REPOSITORY_CREATED: 'REPOSITORY_CREATED',
  REPOSITORY_STARRED: 'REPOSITORY_STARRED',
  REPOSITORY_UNSTARRED: 'REPOSITORY_UNSTARRED',
  REPOSITORY_FORKED: 'REPOSITORY_FORKED',
  PULL_REQUEST_MERGED: 'PULL_REQUEST_MERGED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  USER_FOLLOWED: 'USER_FOLLOWED',
  USER_UNFOLLOWED: 'USER_UNFOLLOWED',
});

export default ACTIVITY_TYPES;
