const ACTIVITY_TYPES = Object.freeze({
  REPOSITORY_CREATED: 'REPOSITORY_CREATED',
  REPOSITORY_STARRED: 'REPOSITORY_STARRED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  USER_FOLLOWED: 'USER_FOLLOWED',
  USER_UNFOLLOWED: 'USER_UNFOLLOWED',
});

export default ACTIVITY_TYPES;
