const ACTIVITY_TYPES = Object.freeze({
  REPOSITORY_CREATED: 'REPOSITORY_CREATED',
  REPOSITORY_STARRED: 'REPOSITORY_STARRED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
});

export default ACTIVITY_TYPES;
